### ISSUE TITLE
发现bug

### ISSUE THREAD

**Issue by loong-chen** [zhao22/as-formula#1]
~~~

 */
    @Test
    public void algebraTest() {
        Formula at = new Formula("t1*(a1+b1-6)");
        Map<String, Object> parameters = new HashMap<>();
        parameters.put("a1", 3.2);
        parameters.put("b1", 5.8);
        parameters.put("t1", 5);
        System.out.println(at.calc(parameters).doubleValue());
        Assert.assertEquals(at.calc(parameters).doubleValue(), 45, 0);
    }
~~~

这种格式的公式会算错，算完括号里的值后，a1 的位置是9，本来应该是3，因为算完9-6后只b1位置
和 6的位置改成了3,。
建议用栈做，算完就出栈。

**Comment by zhao22** [comment]
谢谢




| |
赵鑫
邮箱：seam622@163.com
|

签名由 网易邮箱大师 定制

在2020年03月11日 16:36，loong-chen 写道：


 */

    @Test

    public void algebraTest() {

        Formula at = new Formula("t1*(a1+b1-6)");

        Map<String, Object> parameters = new HashMap<>();

        parameters.put("a1", 3.2);

        parameters.put("b1", 5.8);

        parameters.put("t1", 5);

        System.out.println(at.calc(parameters).doubleValue());

        Assert.assertEquals(at.calc(parameters).doubleValue(), 45, 0);

    }



这种格式的公式会算错，算完括号里的值后，a1 的位置是9，本来应该是3，因为算完9-6后只b1位置
和 6的位置改成了3,。
建议用栈做，算完就出栈。
